server {
    listen 80;
    server_name _;

    location /api/ {
        proxy_pass https://api-service-kyu2.onrender.com/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
        return 200 'Nginx funcionando en Render';
        add_header Content-Type text/plain;
    }
}